# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\"\r\n\x0bPingRequest\";\n\x0cPongResponse\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04load\x18\x03 \x01(\x02\"\r\n\x0bLoadRequest\"\x1c\n\x0cLoadResponse\x12\x0c\n\x04load\x18\x01 \x01(\x02\x32]\n\x0eMonitorService\x12#\n\x04Ping\x12\x0c.PingRequest\x1a\r.PongResponse\x12&\n\x07GetLoad\x12\x0c.LoadRequest\x1a\r.LoadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=17
  _globals['_PINGREQUEST']._serialized_end=30
  _globals['_PONGRESPONSE']._serialized_start=32
  _globals['_PONGRESPONSE']._serialized_end=91
  _globals['_LOADREQUEST']._serialized_start=93
  _globals['_LOADREQUEST']._serialized_end=106
  _globals['_LOADRESPONSE']._serialized_start=108
  _globals['_LOADRESPONSE']._serialized_end=136
  _globals['_MONITORSERVICE']._serialized_start=138
  _globals['_MONITORSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
